# Component Governance pipeline
# results: https://dev.azure.com/CSECodeHub/507909%20-%20SDV%20-%20Programming%20Model%20Developer%20Journey/_componentGovernance/193999?_a=alerts&typeId=11474854&alerts-view-option=active

trigger: none
pr: none

schedules:
  - cron: "0 12 * * 0"
    displayName: Weekly build
    branches:
      include:
      - main
      - ctp2
    always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
